### ISSUE TITLE
Tweak n12 position

### ISSUE THREAD

**Issue by Arpafaucon** [psgparissud/psgparissud.github.io#1]
https://github.com/psgparissud/psgparissud.github.io/blob/1275faae497ff8ecbfdeff2999e9ce38c1b96ed5/index.css#L81

Bravo pour le site :+1: 

j'ai trouvé que ces réglages étaient meilleurs pour `n12`
```css
#n12 {
    right: 49%;
    top: 82%;

    width: 12%;
    height: 15.1%;
}
```
